const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {execFileSync}=require('child_process');
const LABEL='com.bkty.mcptoai.device-agent';
function paths(resourcesPath){const support=path.join(os.homedir(),'Library','Application Support','MCPtoAI'),runtime=path.join(os.homedir(),'Applications','MCPtoAI Device Agent.app'),contents=path.join(runtime,'Contents'),macos=path.join(contents,'MacOS'),resources=path.join(contents,'Resources'),agentDir=path.join(resources,'agent'),exe=path.join(agentDir,'mcptoai-agent'),helper=path.join(resources,'permission-helper'),logs=path.join(os.homedir(),'Library','Logs','MCPtoAI'),plist=path.join(os.homedir(),'Library','LaunchAgents',`${LABEL}.plist`);return {support,runtime,contents,macos,resources,agentDir,exe,helper,logs,plist,source:path.join(resourcesPath,'agent'),helperSource:path.join(resourcesPath,'permission-helper')}}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function hashTree(dir){const h=crypto.createHash('sha256');const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):e.isFile()?[path.join(d,e.name)]:[]).sort();for(const f of walk(dir)){h.update(path.relative(dir,f));h.update('\0');h.update(fs.readFileSync(f));h.update('\0')}return h.digest('hex')}
function bundledVersion(resourcesPath){try{const p=path.join(resourcesPath,'agent-version.json');return JSON.parse(fs.readFileSync(p,'utf8')).version||'0.0.0'}catch{return '0.0.0'}}
function installedVersion(resourcesPath){const p=paths(resourcesPath);try{return JSON.parse(execFileSync('/usr/bin/plutil',['-convert','json','-o','-',path.join(p.contents,'Info.plist')],{encoding:'utf8'})).CFBundleShortVersionString||'0.0.0'}catch{return null}}
function verifySource(p){const sourceExe=path.join(p.source,'mcptoai-agent');if(!fs.existsSync(sourceExe))throw new Error('Bundled agent runtime is missing.');if(process.platform==='darwin'&&process.env.MCPTOAI_ALLOW_UNSIGNED_AGENT!=='1'){for(const [file,label] of [[sourceExe,'Device Agent'],[p.helperSource,'permission helper']]){if(!fs.existsSync(file))throw new Error(`Bundled ${label} is missing.`);try{execFileSync('/usr/bin/codesign',['--verify','--strict','--verbose=2',file],{stdio:'ignore'})}catch{if(!process.defaultApp)throw new Error(`Bundled ${label} signature verification failed.`)}}}const actual=hashTree(p.source);let expected=null;try{expected=JSON.parse(fs.readFileSync(path.join(path.dirname(p.source),'agent-version.json'),'utf8')).sha256}catch{}if(expected&&actual!==expected)throw new Error('Bundled Device Agent integrity check failed.');return {sourceExe,sha256:actual}}
function writeBundle(p,version){fs.mkdirSync(p.macos,{recursive:true});fs.mkdirSync(p.resources,{recursive:true});fs.cpSync(p.source,p.agentDir,{recursive:true});fs.chmodSync(p.exe,0o755);if(fs.existsSync(p.helperSource)){fs.copyFileSync(p.helperSource,p.helper);fs.chmodSync(p.helper,0o755)}const launcher=path.join(p.macos,'mcptoai-device-agent');fs.writeFileSync(launcher,'#!/bin/sh\nHERE="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"\nexec "$HERE/Resources/agent/mcptoai-agent" "$@"\n',{mode:0o755});const info={CFBundleDevelopmentRegion:'en',CFBundleDisplayName:'MCPtoAI Device Agent',CFBundleExecutable:'mcptoai-device-agent',CFBundleIdentifier:'com.bkty.mcptoai.device-agent',CFBundleInfoDictionaryVersion:'6.0',CFBundleName:'MCPtoAI Device Agent',CFBundlePackageType:'APPL',CFBundleShortVersionString:version,CFBundleVersion:String(version).replace(/[^0-9]/g,'')||'1',LSBackgroundOnly:true,NSMicrophoneUsageDescription:'MCPtoAI uses microphone access only when you allow a microphone tool.',NSCameraUsageDescription:'MCPtoAI uses camera access only when you allow a camera tool.'};execFileSync('/usr/bin/plutil',['-convert','xml1','-o',path.join(p.contents,'Info.plist'),'--','-'],{input:JSON.stringify(info)});}
function writeLaunchAgent(p){const work=esc(p.agentDir),out=esc(path.join(p.logs,'agent.log')),err=esc(path.join(p.logs,'agent-error.log')),exe=esc(p.exe);const xml=`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>Label</key><string>${LABEL}</string><key>ProgramArguments</key><array><string>${exe}</string><string>connect</string></array><key>WorkingDirectory</key><string>${work}</string><key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>ThrottleInterval</key><integer>5</integer><key>StandardOutPath</key><string>${out}</string><key>StandardErrorPath</key><string>${err}</string></dict></plist>`;fs.writeFileSync(p.plist,xml,{mode:0o600})}
function stop(){try{execFileSync('launchctl',['bootout',`gui/${process.getuid()}/${LABEL}`],{stdio:'ignore'})}catch{}}
function start(p){execFileSync('launchctl',['bootstrap',`gui/${process.getuid()}`,p.plist]);execFileSync('launchctl',['kickstart',`gui/${process.getuid()}/${LABEL}`],{stdio:'ignore'})}
function health(p){execFileSync(p.exe,['--help'],{stdio:'ignore',timeout:15000});return true}
function install(resourcesPath){if(process.platform!=='darwin')return {ok:true};const p=paths(resourcesPath),version=bundledVersion(resourcesPath),backup=`${p.runtime}.backup`;try{const verified=verifySource(p);stop();fs.mkdirSync(p.support,{recursive:true});fs.mkdirSync(p.logs,{recursive:true});fs.mkdirSync(path.dirname(p.plist),{recursive:true});fs.rmSync(backup,{recursive:true,force:true});if(fs.existsSync(p.runtime))fs.renameSync(p.runtime,backup);try{writeBundle(p,version);writeLaunchAgent(p);health(p);start(p);fs.rmSync(backup,{recursive:true,force:true});return {ok:true,agent_app:p.runtime,version,sha256:verified.sha256}}catch(e){stop();fs.rmSync(p.runtime,{recursive:true,force:true});if(fs.existsSync(backup))fs.renameSync(backup,p.runtime);if(fs.existsSync(p.plist)&&fs.existsSync(p.exe)){try{start(p)}catch{}}throw e}}catch(e){return {ok:false,error:e.message}}}
function versionParts(v){return String(v||'0').split('.').map(x=>parseInt(x,10)||0)}
function compareVersions(a,b){const aa=versionParts(a),bb=versionParts(b),n=Math.max(aa.length,bb.length);for(let i=0;i<n;i++){const d=(aa[i]||0)-(bb[i]||0);if(d)return d>0?1:-1}return 0}
function status(resourcesPath){const p=paths(resourcesPath),installed=installedVersion(resourcesPath),bundled=bundledVersion(resourcesPath);let expected='',installedHash='';try{expected=JSON.parse(fs.readFileSync(path.join(resourcesPath,'agent-version.json'),'utf8')).sha256||''}catch{}try{if(fs.existsSync(p.agentDir))installedHash=hashTree(p.agentDir)}catch{}const cmp=installed?compareVersions(bundled,installed):0;const integrityMismatch=!!installed&&cmp===0&&!!expected&&!!installedHash&&expected!==installedHash;return {installed,bundled,installedHash,expectedHash:expected,integrityMismatch,updateAvailable:!!installed&&(cmp>0||integrityMismatch)}}
function upgradeIfNeeded(resourcesPath){const s=status(resourcesPath);if(!s.installed||!s.updateAvailable)return {ok:true,updated:false,...s};const r=install(resourcesPath);return {...r,updated:!!r.ok,installed:r.ok?r.version:s.installed,bundled:s.bundled}}

module.exports={install,paths,status,bundledVersion,installedVersion,hashTree,compareVersions,upgradeIfNeeded};
