const {app,BrowserWindow,ipcMain,shell,dialog}=require('electron');
const {autoUpdater}=require('electron-updater');
const {compareVersions}=require('./version-compare');
const {spawnSync}=require('child_process');
const path=require('path');const fs=require('fs');const os=require('os');const {installOfficial:installOfficialGitHubMcp}=require('./github-mcp');
const {googleDesktopClientId}=require('./google-oauth-config');const GOOGLE_DESKTOP_CLIENT_ID=String(process.env.MCPTOAI_GOOGLE_DESKTOP_CLIENT_ID||googleDesktopClientId||'').trim();const {adapter}=require('./platform');const {install:installAgent,status:agentUpdateStatus,upgradeIfNeeded:upgradeAgentIfNeeded}=require('./agent-installer');const platform=adapter();
const configRoot=process.platform==='win32'?path.join(process.env.APPDATA||path.join(os.homedir(),'AppData','Roaming'),'MCPtoAI'):path.join(os.homedir(),'.config','mcptoai');
const configPath=path.join(configRoot,'mcp-tools.json');
function readConfig(){try{return JSON.parse(fs.readFileSync(configPath,'utf8'))}catch{return {version:2,tools:{},servers:[]}}}
function writeConfig(data){fs.mkdirSync(path.dirname(configPath),{recursive:true});const tmp=configPath+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2),{mode:0o600});fs.renameSync(tmp,configPath)}
ipcMain.handle('config:get',()=>{const c=readConfig();const toolDefaults={list_dir:'confirm',read_file:'confirm',find_files:'confirm',disk_usage:'auto',running_processes:'auto',write_file:'confirm',open_app:'confirm',capture_screen:'confirm',open_url:'confirm',web_fetch:'auto',generate_image:'confirm',run_command:'confirm',run_in_project:'confirm'};c.tools={...toolDefaults,...(c.tools||{})};const capDefaults={files:'confirm',app_control:'confirm',screen:'confirm',microphone:'deny',camera:'deny'};c.capabilities={...capDefaults,...(c.capabilities||{})};try{const d=JSON.parse(fs.readFileSync(path.join(path.dirname(configPath),'mcp-discovery.json'),'utf8'));c.discovery=d.servers||{}}catch{c.discovery={}}return c});
ipcMain.handle('capability:request-os',(_,name)=>{try{if(process.platform==='win32'){if(name==='microphone'||name==='camera'){shell.openExternal(name==='microphone'?'ms-settings:privacy-microphone':'ms-settings:privacy-webcam');return {ok:true,status:'managed'}}return {ok:true,status:'not-required'}}if(process.platform!=='darwin')return {ok:true,status:'not-required'};if(name==='screen'){const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'permission','request','screen'],{cwd:a.cwd,encoding:'utf8',timeout:30000});const status=(r.stdout||'').trim();return {ok:status==='granted',status,error:(r.stderr||'').trim()}}if(name==='app_control'){const {systemPreferences}=require('electron');const ok=systemPreferences.isTrustedAccessibilityClient(true);return {ok,status:ok?'granted':'not-granted'}}if(name==='files'){shell.openExternal('x-apple.systempreferences:com.apple.preference.security?Privacy_FilesAndFolders');return {ok:true,status:'managed'}}if(name==='microphone'||name==='camera'){const helper=path.join(os.homedir(),'Applications','MCPtoAI Device Agent.app','Contents','Resources','permission-helper');if(!fs.existsSync(helper))return {ok:false,status:'helper-missing',error:'Install / Repair the Device Agent first.'};const r=spawnSync(helper,['request',name],{encoding:'utf8',timeout:65000});const status=(r.stdout||'').trim();return {ok:status==='granted',status,error:(r.stderr||'').trim()}}return {ok:true,status:'not-required'}}catch(e){return {ok:false,status:'error',error:e.message}}});
ipcMain.handle('config:capability-permission',(_,name,permission)=>{const allowed=['files','app_control','screen','microphone','camera'];if(!allowed.includes(name)||!['auto','confirm','deny'].includes(permission))return {ok:false};const c=readConfig();c.capabilities={...(c.capabilities||{}),[name]:permission};const maps={files:['list_dir','read_file','find_files','write_file'],app_control:['open_app'],screen:['capture_screen'],microphone:['capture_microphone'],camera:['capture_camera']};c.tools={...(c.tools||{})};for(const t of maps[name])c.tools[t]=permission;writeConfig(c);return {ok:true}});
ipcMain.handle('config:tool-permission',(_,name,permission)=>{if(!['auto','confirm','deny'].includes(permission))return {ok:false};const c=readConfig();c.tools={...(c.tools||{}),[name]:permission};writeConfig(c);return {ok:true}});
ipcMain.handle('config:server-enabled',(_,id,enabled)=>{const c=readConfig();const server=(c.servers||[]).find(x=>x.id===id);if(!server)return {ok:false};server.enabled=!!enabled;writeConfig(c);return {ok:true}});
ipcMain.handle('config:server-add',(_,draft)=>{const a=agentExecutable(),payload={name:String(draft.name||'').trim(),transport:draft.transport==='stdio'?'stdio':'streamable-http',command:String(draft.command||'').trim(),args:Array.isArray(draft.args)?draft.args.map(String):[],env:draft.env&&typeof draft.env==='object'?draft.env:{},url:String(draft.url||'').trim(),headers:draft.headers&&typeof draft.headers==='object'?draft.headers:{},oauth:draft.oauth&&typeof draft.oauth==='object'?draft.oauth:{}};const r=spawnSync(a.cmd,[...a.prefix,'add-mcp-json'],{cwd:a.cwd,input:JSON.stringify(payload),encoding:'utf8',timeout:15000});if(r.status!==0)return {ok:false,error:(r.stderr||'Could not add MCP server').trim().split('\n').pop()};try{return JSON.parse(r.stdout)}catch{return {ok:false,error:'Invalid MCP response'}}});
ipcMain.handle('config:server-connect',(_,id)=>new Promise(resolve=>{const a=agentExecutable(),{spawn}=require('child_process'),child=spawn(a.cmd,[...a.prefix,'discover-mcp',id],{cwd:a.cwd,stdio:['ignore','pipe','pipe']});let out='',buf='',err='',authOpened=false;child.stdout.on('data',d=>{const text=d.toString();out+=text;buf+=text;const lines=buf.split(/\r?\n/);buf=lines.pop()||'';for(const line of lines){if(!authOpened&&line.startsWith('AUTH_URL ')){authOpened=true;shell.openExternal(line.slice(9).trim())}}});child.stderr.on('data',d=>err+=d.toString());child.on('close',code=>{if(buf){out+=buf.endsWith('\n')?'':'\n'}if(code!==0){const el=out.split(/\r?\n/).find(x=>x.startsWith('MCP_ERROR '));if(el){try{const e=JSON.parse(el.slice(10));return resolve({ok:false,error:e.message||'MCP connection failed',title:e.title||'MCP connection failed',code:e.code||'connection_failed',detail:e.detail||''})}catch{}}return resolve({ok:false,error:'MCPtoAI could not complete the connection.',title:'MCP connection failed',code:'connection_failed',detail:err.trim().slice(-1200)})}const line=out.split(/\r?\n/).find(x=>x.startsWith('TOOLS '));if(!line)return resolve({ok:false,error:'MCP connected but tool discovery returned no result.'});try{const tools=JSON.parse(line.slice(6)),file=path.join(path.dirname(configPath),'mcp-discovery.json');let d={version:1,servers:{}};try{d=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}d.servers={...(d.servers||{}),[id]:tools};fs.writeFileSync(file,JSON.stringify(d,null,2),{mode:0o600});resolve({ok:true,tools})}catch(e){resolve({ok:false,error:e.message})}});child.on('error',e=>resolve({ok:false,error:e.message}))}));
ipcMain.handle('config:server-remove',(_,id)=>{const c=readConfig(),target=(c.servers||[]).find(x=>x.id===id),a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'remove-mcp',String(id)],{cwd:a.cwd,encoding:'utf8',timeout:15000});if(r.status!==0)return {ok:false};clearDiscovery(String(id));if(target?.managed_integration==='github-official'){const marker=path.join(configRoot,'integrations','github','.cleanup-pending');try{fs.mkdirSync(path.dirname(marker),{recursive:true});fs.writeFileSync(marker,'1',{mode:0o600})}catch{}}try{return JSON.parse(r.stdout)}catch{return {ok:false}}});

function discoveryFile(){return path.join(path.dirname(configPath),'mcp-discovery.json')}
function saveDiscovery(id,tools){const file=discoveryFile();let d={version:1,servers:{}};try{d=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}d.servers={...(d.servers||{}),[id]:tools};fs.writeFileSync(file,JSON.stringify(d,null,2),{mode:0o600})}
function clearDiscovery(id){const file=discoveryFile();try{const d=JSON.parse(fs.readFileSync(file,'utf8'));if(d.servers&&id in d.servers){delete d.servers[id];fs.writeFileSync(file,JSON.stringify(d,null,2),{mode:0o600})}}catch{}}
function cleanupGitHubIntegrationDirs(activeCommand=''){const base=path.join(configRoot,'integrations','github');let keep='';try{keep=activeCommand?path.basename(path.dirname(activeCommand)):''}catch{}try{for(const e of fs.readdirSync(base,{withFileTypes:true})){if(e.isDirectory()&&e.name!==keep)try{fs.rmSync(path.join(base,e.name),{recursive:true,force:true})}catch{}}}catch{}}
function githubAuthProbe(server){if(!server?.id||!server.command||!fs.existsSync(server.command))return false;try{const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'github-auth-status',server.id],{cwd:a.cwd,encoding:'utf8',timeout:20000});return r.status===0&&String(r.stdout||'').trim()==='authorized'}catch{return false}}
ipcMain.handle('tools:github-status',()=>{const c=readConfig(),server=(c.servers||[]).find(x=>x.managed_integration==='github-official');if(!server){const marker=path.join(configRoot,'integrations','github','.cleanup-pending');if(fs.existsSync(marker)){cleanupGitHubIntegrationDirs('');try{fs.rmSync(path.join(configRoot,'integrations','github'),{recursive:true,force:true})}catch{}}}let installed=false,version='';if(server&&server.command){installed=fs.existsSync(server.command);const m=String(server.command).match(/[\/]github[\/]([^\/]+)[\/]/);version=m?m[1]:''}let tools=[];try{const d=JSON.parse(fs.readFileSync(discoveryFile(),'utf8'));tools=server?(d.servers?.[server.id]||[]):[]}catch{}const authorized=githubAuthProbe(server);return {installed,configured:!!server,authorized,connected:!!server&&installed&&authorized&&tools.length>0,server_id:server?.id||'',version,tools:tools.length,read_only:!!server?.args?.includes('--read-only')}});
ipcMain.handle('tools:github-connect',async(_,v)=>{try{const token=String(v?.token||'').trim(),readOnly=v?.read_only!==false;if(!token||token.length<20||token.length>512||/\s/.test(token))return {ok:false,error:'Enter a valid GitHub Personal Access Token.'};const a=agentExecutable();const existing=(readConfig().servers||[]).find(x=>x.managed_integration==='github-official');const pkg=await installOfficialGitHubMcp(configRoot);const payload={name:'GitHub',transport:'stdio',command:pkg.binary,args:readOnly?['stdio','--read-only']:['stdio'],env:{GITHUB_PERSONAL_ACCESS_TOKEN:token},url:'',headers:{}},r=spawnSync(a.cmd,[...a.prefix,'add-mcp-json'],{cwd:a.cwd,input:JSON.stringify(payload),encoding:'utf8',timeout:15000});if(r.status!==0)return {ok:false,error:(r.stderr||'Could not add GitHub MCP').trim().split('\n').pop()};let out;try{out=JSON.parse(r.stdout)}catch{return {ok:false,error:'Invalid MCPtoAI Agent response'}}if(!out?.ok||!out.id)return {ok:false,error:out?.error||'Could not add GitHub MCP'};let c=readConfig(),server=(c.servers||[]).find(x=>x.id===out.id);if(!server)return {ok:false,error:'GitHub MCP configuration was not saved.'};server.managed_integration='github-official';server.official_version=pkg.version;server.official_sha256=pkg.sha256;server.auth_mode='pat';server.read_only=readOnly;writeConfig(c);const rollback=()=>{spawnSync(a.cmd,[...a.prefix,'remove-mcp',out.id],{cwd:a.cwd,encoding:'utf8',timeout:15000});clearDiscovery(out.id)};const dr=spawnSync(a.cmd,[...a.prefix,'discover-mcp',out.id],{cwd:a.cwd,encoding:'utf8',timeout:30000});if(dr.status!==0){rollback();return {ok:false,error:'GitHub MCP started but tool discovery failed. Your existing GitHub connection was kept.'}}const line=String(dr.stdout||'').split(/\r?\n/).find(x=>x.startsWith('TOOLS '));let tools=[];try{tools=line?JSON.parse(line.slice(6)):[]}catch{}if(!tools.length){rollback();return {ok:false,error:'GitHub MCP returned no tools. Your existing GitHub connection was kept.'}}saveDiscovery(out.id,tools);server=(readConfig().servers||[]).find(x=>x.id===out.id);if(!githubAuthProbe(server)){rollback();return {ok:false,error:'GitHub rejected this token. Your existing GitHub connection was kept.'}}if(existing&&existing.id!==out.id){spawnSync(a.cmd,[...a.prefix,'remove-mcp',existing.id],{cwd:a.cwd,encoding:'utf8',timeout:15000});clearDiscovery(existing.id)}await platform.restart();cleanupGitHubIntegrationDirs(pkg.binary);return {ok:true,id:out.id,version:pkg.version,tools:tools.length,read_only:readOnly,message:`GitHub connected with ${tools.length} authenticated tools${readOnly?' in read-only mode':''}.`}}catch(e){return {ok:false,error:String(e?.message||e)}}});
ipcMain.handle('tools:github-token-page',()=>{shell.openExternal('https://github.com/settings/personal-access-tokens/new');return {ok:true}});
ipcMain.handle('tools:gdrive-status',()=>{try{const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'google-drive-status'],{cwd:a.cwd,encoding:'utf8',timeout:10000});if(r.status!==0)return {configured:false,authorized:false,connected:false,selected:0,mode:'',error:(r.stderr||'').trim()};const d=JSON.parse(r.stdout||'{}');const c=readConfig(),server=(c.servers||[]).find(x=>x.managed_integration==='google-drive-picker');let tools=[];try{const disc=JSON.parse(fs.readFileSync(path.join(path.dirname(configPath),'mcp-discovery.json'),'utf8'));tools=server?(disc.servers?.[server.id]||[]):[]}catch{}return {...d,connected:!!(d.authorized&&server&&tools.length),server_id:server?.id||'',tools:tools.length}}catch(e){return {configured:false,authorized:false,connected:false,selected:0,mode:'',error:String(e.message||e)}}});
ipcMain.handle('tools:gdrive-connect',async(_,draft={})=>{try{
  const a=agentExecutable();
  let c=readConfig();
  const legacy=(c.servers||[]).filter(x=>x.managed_integration==='google-drive-official');
  for(const old of legacy){spawnSync(a.cmd,[...a.prefix,'remove-mcp',old.id],{cwd:a.cwd,encoding:'utf8',timeout:15000});try{const file=path.join(path.dirname(configPath),'mcp-discovery.json'),disc=JSON.parse(fs.readFileSync(file,'utf8'));delete disc.servers?.[old.id];fs.writeFileSync(file,JSON.stringify(disc,null,2),{mode:0o600})}catch{}}
  c=readConfig();let server=(c.servers||[]).find(x=>x.managed_integration==='google-drive-picker');
  if(!server){
    const payload={name:'Google Drive',transport:'stdio',command:a.cmd,args:[...a.prefix,'google-drive-mcp'],env:{},url:'',headers:{}};
    const add=spawnSync(a.cmd,[...a.prefix,'add-mcp-json'],{cwd:a.cwd,input:JSON.stringify(payload),encoding:'utf8',timeout:15000});
    if(add.status!==0)return {ok:false,error:(add.stderr||'Could not add Google Drive local MCP').trim().split('\n').pop()};
    let out;try{out=JSON.parse(add.stdout)}catch{return {ok:false,error:'Invalid MCPtoAI Agent response'}}
    c=readConfig();server=(c.servers||[]).find(x=>x.id===out.id);if(!server)return {ok:false,error:'Google Drive local MCP configuration was not saved.'};
    server.managed_integration='google-drive-picker';writeConfig(c);
  }
  return await new Promise(resolve=>{
    const {spawn}=require('child_process');const child=spawn(a.cmd,[...a.prefix,'google-drive-auth-json'],{cwd:a.cwd,stdio:['pipe','pipe','pipe'],env:{...process.env,MCPTOAI_GOOGLE_DESKTOP_CLIENT_ID:GOOGLE_DESKTOP_CLIENT_ID}});
    let out='',buf='',err='',opened=false;child.stdin.end(JSON.stringify({mode:draft.mode==='byo'?'byo':'managed',client_id:String(draft.client_id||''),client_secret:String(draft.client_secret||''),append:!!draft.append}));
    child.stdout.on('data',d=>{const text=d.toString();out+=text;buf+=text;const lines=buf.split(/\r?\n/);buf=lines.pop()||'';for(const line of lines){if(!opened&&line.startsWith('AUTH_URL ')){opened=true;shell.openExternal(line.slice(9).trim())}}});
    child.stderr.on('data',d=>err+=d.toString());
    child.on('close',async code=>{if(code!==0){const line=out.split(/\r?\n/).find(x=>x.startsWith('GOOGLE_DRIVE_ERROR '));if(line){try{return resolve({ok:false,error:JSON.parse(line.slice(19)).error||'Google Drive connection failed'})}catch{}}return resolve({ok:false,error:(err||'Google Drive connection failed').trim().split('\n').pop()})}
      const line=out.split(/\r?\n/).find(x=>x.startsWith('GOOGLE_DRIVE_AUTH '));let auth={};try{auth=JSON.parse(line?.slice(18)||'{}')}catch{}
      const cr=await new Promise(done=>{const child2=spawn(a.cmd,[...a.prefix,'discover-mcp',server.id],{cwd:a.cwd,stdio:['ignore','pipe','pipe']});let o='',e='';child2.stdout.on('data',d=>o+=d.toString());child2.stderr.on('data',d=>e+=d.toString());child2.on('close',code2=>{if(code2!==0)return done({ok:false,error:(e||o||'Google Drive MCP discovery failed').trim().split('\n').pop()});const tl=o.split(/\r?\n/).find(x=>x.startsWith('TOOLS '));if(!tl)return done({ok:false,error:'Google Drive MCP returned no tools'});try{const tools=JSON.parse(tl.slice(6)),file=path.join(path.dirname(configPath),'mcp-discovery.json');let disc={version:1,servers:{}};try{disc=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}disc.servers={...(disc.servers||{}),[server.id]:tools};fs.writeFileSync(file,JSON.stringify(disc,null,2),{mode:0o600});done({ok:true,tools})}catch(ex){done({ok:false,error:ex.message})}})});
      if(!cr.ok)return resolve(cr);await platform.restart();resolve({ok:true,id:server.id,tools:cr.tools,selected:auth.selected||0,added:auth.added||0,mode:auth.mode||draft.mode||'managed'});
    });child.on('error',e=>resolve({ok:false,error:e.message}));
  });
}catch(e){return {ok:false,error:String(e?.message||e)}}});
ipcMain.handle('tools:gdrive-disconnect',async()=>{try{const c=readConfig(),servers=(c.servers||[]).filter(x=>['google-drive-picker','google-drive-official'].includes(x.managed_integration)),a=agentExecutable();spawnSync(a.cmd,[...a.prefix,'google-drive-disconnect'],{cwd:a.cwd,encoding:'utf8',timeout:10000});for(const server of servers)spawnSync(a.cmd,[...a.prefix,'remove-mcp',server.id],{cwd:a.cwd,encoding:'utf8',timeout:15000});try{const file=path.join(path.dirname(configPath),'mcp-discovery.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));for(const server of servers)delete d.servers?.[server.id];fs.writeFileSync(file,JSON.stringify(d,null,2),{mode:0o600})}catch{}await platform.restart();return {ok:true}}catch(e){return {ok:false,error:String(e?.message||e)}}});
ipcMain.handle('config:server-tool-permission',(_,id,name,permission)=>{if(!['auto','confirm','deny'].includes(permission))return {ok:false};const c=readConfig();const server=(c.servers||[]).find(x=>x.id===id);if(!server)return {ok:false};server.tools={...(server.tools||{}),[name]:permission};writeConfig(c);return {ok:true}});

const settingsPath=path.join(path.dirname(configPath),'settings.json');
function readSettings(){try{return JSON.parse(fs.readFileSync(settingsPath,'utf8'))}catch{return {}}}
function writeSettings(v){fs.mkdirSync(path.dirname(settingsPath),{recursive:true});const tmp=settingsPath+'.tmp';fs.writeFileSync(tmp,JSON.stringify(v,null,2),{mode:0o600});fs.renameSync(tmp,settingsPath)}
ipcMain.handle('history:storage-get',()=>{const c=readSettings(),provider=['mcptoai','local'].includes(c.history_provider)?c.history_provider:'mcptoai';return {provider,options:[{id:'mcptoai',label:'MCPtoAI Cloud',available:true},{id:'local',label:'This device only',available:true},{id:'remote',label:'My own server',available:false,coming_soon:true,enterprise:true}]}});
ipcMain.handle('history:storage-set',(_,provider)=>{provider=String(provider||'').trim().toLowerCase();if(!['mcptoai','local'].includes(provider))return {ok:false,error:'Unsupported history storage provider'};const c=readSettings();c.history_provider=provider;writeSettings(c);return {ok:true,provider}});
ipcMain.handle('workspace:get',()=>{const c=readSettings();const chosen=String(c.workspace_root||'').trim();return {path:chosen||'',configured:!!chosen,defaults:chosen?[]:[path.join(os.homedir(),'Desktop'),path.join(os.homedir(),'Documents'),path.join(os.homedir(),'Downloads')]};});
ipcMain.handle('workspace:choose',async()=>{const r=await dialog.showOpenDialog({title:'Choose MCPtoAI workspace',properties:['openDirectory','createDirectory']});if(r.canceled||!r.filePaths[0])return {ok:false,canceled:true};let selected;try{selected=fs.realpathSync(r.filePaths[0]);if(!fs.statSync(selected).isDirectory())return {ok:false,error:'Selected path is not a folder.'}}catch(e){return {ok:false,error:e.message}}const c=readSettings();c.workspace_root=selected;writeSettings(c);await platform.restart();return {ok:true,path:selected};});
function installedAgentPath(){if(process.platform==='darwin')return path.join(os.homedir(),'Applications','MCPtoAI Device Agent.app','Contents','Resources','agent','mcptoai-agent');if(process.platform==='win32')return path.join(process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local'),'MCPtoAI','Agent','mcptoai-agent.exe');return ''}
function agentExecutable(){if(!app.isPackaged){const root=path.resolve(__dirname,'..','..'),agentDir=path.join(root,'device-agent'),py=process.platform==='win32'?path.join(agentDir,'.venv','Scripts','python.exe'):path.join(agentDir,'.venv','bin','python');if(fs.existsSync(py))return {cmd:py,prefix:['-m','mcptoai_agent'],cwd:agentDir}}const installed=installedAgentPath();if(installed&&fs.existsSync(installed))return {cmd:installed,prefix:[],cwd:path.dirname(installed)};const bundled=path.join(process.resourcesPath,'agent',process.platform==='win32'?'mcptoai-agent.exe':'mcptoai-agent');if(fs.existsSync(bundled))return {cmd:bundled,prefix:[],cwd:path.dirname(bundled)};throw new Error('Bundled MCPtoAI agent is unavailable. Use Install / Repair.')}
ipcMain.handle('provider:detect-local',async()=>{const targets=[{id:'ollama',url:'http://127.0.0.1:11434/v1/models'},{id:'lmstudio',url:'http://127.0.0.1:1234/v1/models'}];return Promise.all(targets.map(async t=>{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),1200);try{const r=await fetch(t.url,{signal:ctrl.signal});if(!r.ok)return {id:t.id,running:false};const d=await r.json();return {id:t.id,running:true,models:Array.isArray(d.data)?d.data.map(x=>x.id).filter(Boolean):[]}}catch{return {id:t.id,running:false,models:[]}}finally{clearTimeout(timer)}}))});
ipcMain.handle('provider:status',()=>{const cfg=readSettings(),a=agentExecutable(),rr=spawnSync(a.cmd,[...a.prefix,'provider-registry'],{cwd:a.cwd,encoding:'utf8',timeout:5000});let registry={};try{registry=JSON.parse(rr.stdout)}catch{return {provider:cfg.provider,model:cfg.model,openai_base_url:cfg.openai_base_url||'',providers:[],error:(rr.stderr||'Could not load provider registry').trim()}}const providers=Object.entries(registry).map(([id,meta])=>({id,...meta,has_key:!!meta.has_key}));const fallback=providers.find(p=>p.has_key)?.id||providers[0]?.id||'';const active=cfg.provider||fallback;return {provider:active,model:cfg.model||(active==='evren'?'deepseek-v4.1-flash':''),openai_base_url:cfg.openai_base_url||'',replicate_image_model:cfg.replicate_image_model||'black-forest-labs/flux-1.1-pro',providers}});
ipcMain.handle('provider:probe',(_,v)=>{const a=agentExecutable(),env={...process.env,MCPTOAI_PROVIDER:String(v.provider||''),MCPTOAI_MODEL:String(v.model||'')};if(v.openai_base_url)env.MCPTOAI_OPENAI_BASE_URL=String(v.openai_base_url);else delete env.MCPTOAI_OPENAI_BASE_URL;const r=spawnSync(a.cmd,[...a.prefix,'probe-provider'],{cwd:a.cwd,encoding:'utf8',timeout:60000,env});if(r.status!==0){const lines=(r.stderr||'Provider probe failed').trim().split('\n');const meaningful=lines.findLast(x=>/^(RuntimeError|ValueError|AttributeError|TypeError|Error):/.test(x.trim()))||lines.findLast(x=>!x.includes('[PYI-'))||lines.at(-1);return {ok:false,error:meaningful.trim()}};try{return JSON.parse(r.stdout)}catch{return {ok:false,error:'Invalid provider probe response'}}});
ipcMain.handle('provider:list-models',(_,v)=>{const a=agentExecutable(),env={...process.env,MCPTOAI_PROVIDER:String(v.provider||''),MCPTOAI_MODEL:String(v.model||'local-model')};if(v.openai_base_url)env.MCPTOAI_OPENAI_BASE_URL=String(v.openai_base_url);else delete env.MCPTOAI_OPENAI_BASE_URL;const r=spawnSync(a.cmd,[...a.prefix,'list-models'],{cwd:a.cwd,encoding:'utf8',timeout:12000,env});if(r.status!==0)return {ok:false,error:(r.stderr||'Could not connect to provider').trim().split('\n').findLast(x=>!x.includes('[PYI-'))||'Could not connect to provider'};try{const d=JSON.parse(r.stdout);return d.ok===false?d:{ok:true,models:Array.isArray(d)?d:(d.models||[])}}catch{return {ok:false,error:'Invalid model response'}}});
ipcMain.handle('provider:add-custom',(_,v)=>{const name=String(v.name||'').trim().slice(0,80),base=String(v.base_url||'').trim();if(!name||!/^https?:\/\//.test(base))return {ok:false,error:'Name and valid HTTP(S) base URL are required'};const c=readSettings(),id='custom-'+require('crypto').randomBytes(6).toString('hex');c.custom_providers={...(c.custom_providers||{}),[id]:{name,base_url:base,key:true}};writeSettings(c);return {ok:true,id}});
ipcMain.handle('provider:remove-custom',(_,id)=>{if(!/^custom-[a-f0-9]{12}$/.test(String(id)))return {ok:false};const c=readSettings();if(!c.custom_providers?.[id])return {ok:false};delete c.custom_providers[id];if(c.provider===id){c.provider='evren';c.model='';c.openai_base_url=null}writeSettings(c);const a=agentExecutable();spawnSync(a.cmd,[...a.prefix,'remove-key',id],{cwd:a.cwd,encoding:'utf8',timeout:10000});return {ok:true}});
ipcMain.handle('provider:save',(_,v)=>{const a=agentExecutable(),rr=spawnSync(a.cmd,[...a.prefix,'provider-registry'],{cwd:a.cwd,encoding:'utf8',timeout:5000});let reg={};try{reg=JSON.parse(rr.stdout)}catch{}if(!reg[v.provider])return {ok:false,error:'Unsupported provider'};const model=String(v.model||'').trim();if(!model)return {ok:false,error:'Model is required'};const base=String(v.openai_base_url||'').trim();if(['local','custom'].includes(v.provider)&&!/^https?:\/\//.test(base))return {ok:false,error:'A valid HTTP(S) base URL is required'};const current=readSettings();writeSettings({...current,provider:v.provider,model,openai_base_url:base||null});return {ok:true}});
ipcMain.handle('provider:save-replicate-model',(_,model)=>{const value=String(model||'').trim();if(!/^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/.test(value)||value.length>160)return {ok:false,error:'Use a Replicate model slug such as black-forest-labs/flux-1.1-pro'};const c=readSettings();c.replicate_image_model=value;writeSettings(c);return {ok:true,model:value}});
ipcMain.handle('provider:set-key',(_,provider,key)=>{if(!/^[a-z0-9_-]{1,64}$/.test(String(provider||''))||!String(key||'').trim())return {ok:false};const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'set-key',provider,'--stdin'],{cwd:a.cwd,input:String(key).trim()+'\n',encoding:'utf8',timeout:15000});if(r.status===0){const c=readSettings(),keys=new Set(c.configured_provider_keys||[]);keys.add(provider);c.configured_provider_keys=[...keys];writeSettings(c)}return {ok:r.status===0,error:r.status===0?'':'Could not save API key'}});
ipcMain.handle('provider:remove-key',(_,provider)=>{const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'remove-key',provider],{cwd:a.cwd,encoding:'utf8',timeout:15000});if(r.status===0){const c=readSettings();c.configured_provider_keys=(c.configured_provider_keys||[]).filter(x=>x!==provider);writeSettings(c)}return {ok:r.status===0}});

function create(){const w=new BrowserWindow({width:1120,height:760,minWidth:900,minHeight:620,title:'MCPtoAI',backgroundColor:'#090b10',icon:path.join(__dirname,'..','build','icon.png'),webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});w.loadFile(path.join(__dirname,'index.html'));}
ipcMain.handle('permissions:status',()=>{if(process.platform!=='darwin')return {platform:process.platform,accessibility:null,fullDisk:null};const {systemPreferences}=require('electron');return {platform:'darwin',accessibility:systemPreferences.isTrustedAccessibilityClient(false),fullDisk:null}});
ipcMain.handle('permissions:request-accessibility',()=>{if(process.platform!=='darwin')return false;const {systemPreferences}=require('electron');return systemPreferences.isTrustedAccessibilityClient(true)});
ipcMain.handle('permissions:reveal-agent',()=>{if(process.platform!=='darwin')return false;const p=path.join(os.homedir(),'Applications','MCPtoAI Device Agent.app');if(!fs.existsSync(p))return false;shell.showItemInFolder(p);return true});
ipcMain.handle('permissions:open',(_,kind)=>{if(process.platform==='win32'){const panes={microphone:'ms-settings:privacy-microphone',camera:'ms-settings:privacy-webcam',files:'ms-settings:privacy-broadfilesystemaccess',screen:'ms-settings:privacy-screenshots'};if(!panes[kind])return false;shell.openExternal(panes[kind]);return true}if(process.platform!=='darwin')return false;const panes={accessibility:'x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility',fullDisk:'x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles',files:'x-apple.systempreferences:com.apple.preference.security?Privacy_FilesAndFolders',screen:'x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture',microphone:'x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone',camera:'x-apple.systempreferences:com.apple.preference.security?Privacy_Camera'};if(!panes[kind])return false;shell.openExternal(panes[kind]);return true});
ipcMain.handle('agent:status',()=>platform.status());
ipcMain.handle('agent:install',()=>installAgent(process.resourcesPath));
ipcMain.handle('permissions:mark-seen',()=>{const c=readSettings();c.permissions_onboarding_seen=true;writeSettings(c);return {ok:true}});
ipcMain.handle('agent:paired',()=>{const exe=installedAgentPath();if(!exe||!fs.existsSync(exe))return {installed:false,paired:false};const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'pair-status'],{cwd:a.cwd,encoding:'utf8',timeout:10000});const paired=r.status===0&&String(r.stdout||'').trim()==='paired';const c=readSettings();if(c.device_paired!==paired){c.device_paired=paired;writeSettings(c)}return {installed:true,paired,permissions_seen:c.permissions_onboarding_seen===true}});
ipcMain.handle('agent:logout',async()=>{await platform.stop();await new Promise(r=>setTimeout(r,500));const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'logout'],{cwd:a.cwd,encoding:'utf8',timeout:30000});if(r.status!==0)return {ok:false,error:'Could not disconnect this device.'};const check=spawnSync(a.cmd,[...a.prefix,'pair-status'],{cwd:a.cwd,encoding:'utf8',timeout:10000});const unpaired=check.status===0&&String(check.stdout||'').trim()==='unpaired';if(!unpaired)return {ok:false,error:'Device credentials could not be cleared.'};const c=readSettings();c.device_paired=false;writeSettings(c);return {ok:true}});
ipcMain.handle('agent:clear-data',()=>{const a=agentExecutable(),r=spawnSync(a.cmd,[...a.prefix,'clear-local-data'],{cwd:a.cwd,encoding:'utf8',timeout:30000});return {ok:r.status===0,error:r.status===0?'':'Could not remove local data.'}});
ipcMain.handle('agent:login',async()=>{const exe=installedAgentPath();if(!exe||!fs.existsSync(exe))return {ok:false,error:'Install the agent first.'};return new Promise(resolve=>{const {spawn}=require('child_process');const child=spawn(exe,['login'],{stdio:['ignore','pipe','pipe']});let buf='',opened=false;child.stdout.on('data',d=>{buf+=d.toString();const lines=buf.split(/\r?\n/);buf=lines.pop()||'';for(const line of lines){if(opened)continue;const m=line.match(/https:\/\/[^\s]+/);if(m){opened=true;shell.openExternal(m[0])}}});child.on('close',code=>{if(code===0){const c=readSettings();c.device_paired=true;writeSettings(c)}resolve({ok:code===0,error:code===0?'':'Device pairing was not completed.'})});child.on('error',e=>resolve({ok:false,error:e.message}))})});
ipcMain.handle('agent:action',async(_,action)=>['start','stop','restart'].includes(action)?platform[action]():({ok:false}));
ipcMain.handle('app:info',()=>({platform:platform.platform,version:app.getVersion(),arch:process.arch}));
autoUpdater.autoDownload=false;
autoUpdater.autoInstallOnAppQuit=true;
autoUpdater.allowPrerelease=false;
const otaPlatform=process.platform==='win32'?'windows':'macos';
autoUpdater.setFeedURL({provider:'generic',url:'https://api.mcptoai.com/releases/'+otaPlatform+'/'});
let otaDownloaded=false;
ipcMain.handle('updates:desktop-download',async()=>{
  if(!app.isPackaged)return {ok:false,error:'OTA updates are available in packaged builds only.'};
  try{const r=await autoUpdater.checkForUpdates();const v=r?.updateInfo?.version||'',current=app.getVersion();if(!v||compareVersions(v,current)<=0)return {ok:true,available:false,current,latest:v||current};await autoUpdater.downloadUpdate();otaDownloaded=true;return {ok:true,available:true,downloaded:true,version:v}}catch(e){return {ok:false,error:String(e?.message||e)}}
});
ipcMain.handle('updates:desktop-install',()=>{if(!otaDownloaded)return {ok:false,error:'No downloaded update is ready.'};setImmediate(()=>autoUpdater.quitAndInstall(false,true));return {ok:true}});
ipcMain.handle('updates:agent-status',()=>agentUpdateStatus(process.resourcesPath));
ipcMain.handle('updates:agent-install',()=>installAgent(process.resourcesPath));
ipcMain.handle('updates:agent-auto-upgrade',()=>upgradeAgentIfNeeded(process.resourcesPath));
ipcMain.handle('updates:check',async()=>{
  const updatePlatform=process.platform==='win32'?'windows':'macos';
  const endpoint=`https://api.mcptoai.com/api/updates/${updatePlatform}.json`;
  try{
    const res=await fetch(endpoint,{headers:{'Accept':'application/json','User-Agent':`MCPtoAI/${app.getVersion()}`}});
    if(!res.ok)return {ok:false,error:`Update service returned HTTP ${res.status}.`,endpoint};
    const manifest=await res.json();
    const current=app.getVersion(),desktopVersion=String(manifest?.desktop?.version||'');return {ok:true,current,platform:process.platform,arch:process.arch,agent:agentUpdateStatus(process.resourcesPath),manifest,desktopUpdateAvailable:compareVersions(desktopVersion,current)>0,endpoint};
  }catch(e){return {ok:false,error:'Update service is not available yet.',detail:String(e&&e.message||e),endpoint}}
});
let desktopChatProcess=null,desktopChatBuffer='',desktopChatWaiters=new Map();
// Terminal komutları: yerel izin. Agent'ın shell-access komutuyla okunur/yazılır; web ya da
// relay bu izni değiştiremez. Araçlar başlangıçta kaydedildiği için değişiklikten sonra agent
// ve yerel sohbet süreci yeniden başlatılır.
function shellAccess(action){const a=agentExecutable(),{spawnSync}=require('child_process');const r=spawnSync(a.cmd,[...a.prefix,'shell-access',action],{cwd:a.cwd,encoding:'utf8',timeout:20000});if(r.status!==0)return {ok:false,error:(r.stderr||'').trim().split('\n').pop()||'shell-access failed'};try{const lines=String(r.stdout||'').trim().split(/\r?\n/);return {ok:true,...JSON.parse(lines[lines.length-1])}}catch{return {ok:false,error:'Unexpected agent response'}}}
ipcMain.handle('shell:access',()=>shellAccess('status'));
ipcMain.handle('shell:set-access',async(_,on)=>{const r=shellAccess(on===true?'on':'off');if(!r.ok)return r;if(desktopChatProcess){try{desktopChatProcess.kill()}catch{}desktopChatProcess=null}try{await platform.restart()}catch{}return r});
function ensureDesktopChat(){if(desktopChatProcess&&!desktopChatProcess.killed)return desktopChatProcess;const a=agentExecutable(),{spawn}=require('child_process');desktopChatProcess=spawn(a.cmd,[...a.prefix,'desktop-chat-jsonl'],{cwd:a.cwd,stdio:['pipe','pipe','pipe']});desktopChatBuffer='';desktopChatProcess.stdout.on('data',chunk=>{desktopChatBuffer+=chunk.toString();const lines=desktopChatBuffer.split(/\r?\n/);desktopChatBuffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;let msg;try{msg=JSON.parse(line)}catch{continue}const sid=msg.session_id,w=desktopChatWaiters.get(sid);if(msg.kind==='approval_required'){rememberApproval(msg);BrowserWindow.getAllWindows()[0]?.webContents.send('chat:approval',msg);continue}if(msg.kind==='event'){BrowserWindow.getAllWindows()[0]?.webContents.send('chat:event',msg);if(w){w.events.push(msg.event);if(msg.event?.type==='text')w.text=msg.event.text}continue}if(msg.kind==='turn_done'&&w){desktopChatWaiters.delete(sid);w.resolve({ok:true,text:w.text||'',events:w.events||[]})}}});desktopChatProcess.on('exit',()=>{for(const [,w] of desktopChatWaiters){w.resolve({ok:false,error:'Local chat agent stopped.'})}desktopChatWaiters.clear();desktopChatProcess=null});return desktopChatProcess}
ipcMain.handle('chat:pick-files',async()=>{const r=await dialog.showOpenDialog({properties:['openFile','multiSelections'],filters:[{name:'Images & text',extensions:['png','jpg','jpeg','webp','gif','txt','md','json','csv','log','py','js','ts','tsx','jsx','html','css','yaml','yml','xml','sql']}]});if(r.canceled)return {ok:true,files:[]};const out=[];let total=0;for(const file of r.filePaths.slice(0,8)){const st=fs.statSync(file);if(st.size>256*1024)continue;const ext=path.extname(file).toLowerCase(),name=path.basename(file),buf=fs.readFileSync(file);total+=buf.length;if(total>512*1024)break;if(['.png','.jpg','.jpeg','.webp','.gif'].includes(ext)){const mime=ext==='.png'?'image/png':ext==='.webp'?'image/webp':ext==='.gif'?'image/gif':'image/jpeg';out.push({kind:'image',name,data_url:`data:${mime};base64,${buf.toString('base64')}`})}else out.push({kind:'text',name,text:buf.toString('utf8')})}return {ok:true,files:out}});
ipcMain.handle('chat:local',(_,payload)=>new Promise(resolve=>{const text=String(payload?.text||'').trim();if(!text||Buffer.byteLength(text)>256*1024)return resolve({ok:false,error:'Invalid message'});const sid=String(payload?.session_id||'local').slice(0,128);if(desktopChatWaiters.has(sid))return resolve({ok:false,error:'A message is already running in this local chat.'});const child=ensureDesktopChat();desktopChatWaiters.set(sid,{resolve,text:'',events:[]});child.stdin.write(JSON.stringify({type:'message',session_id:sid,text,language:payload?.language||null,provider:String(payload?.provider||'').slice(0,80),model:String(payload?.model||'').slice(0,160),images:Array.isArray(payload?.images)?payload.images.slice(0,8):[],preferred_mcp_server_ids:Array.isArray(payload?.preferred_mcp_server_ids)?payload.preferred_mcp_server_ids.slice(0,32):[],capability:String(payload?.capability||'').slice(0,40),context:Array.isArray(payload?.context)?payload.context.slice(-40):[]})+'\n')}));
ipcMain.handle('chat:cancel',(_,v)=>{const sid=String(v?.session_id||'local').slice(0,128),w=desktopChatWaiters.get(sid),child=desktopChatProcess;if(!w||!child||child.killed)return {ok:false,error:'No local message is running.'};child.stdin.write(JSON.stringify({type:'cancel',session_id:sid})+'\n');return {ok:true}});
// Agent onayı yalnızca isteyen oturum için kabul eder (session_id kontrolü). Oturum kimliği
// arayüzden alınmaz; approval_required iletilirken main süreçte saklanan kayıttan eklenir.
// Her onay tek kullanımlıktır. Agent en fazla 2 saat bekler (MCPTOAI_APPROVAL_TIMEOUT); kayıt da o süreden
// kısa bir süre sonra düşer.
const APPROVAL_TTL_MS=(Number(process.env.MCPTOAI_APPROVAL_TIMEOUT)||7200)*1000+5000;
const pendingChatApprovals=new Map();
function rememberApproval(msg){const aid=String(msg?.approval_id||''),sid=String(msg?.session_id||'');if(!/^[a-f0-9]{32}$/i.test(aid)||!sid)return;pendingChatApprovals.set(aid,{sid,timer:setTimeout(()=>pendingChatApprovals.delete(aid),APPROVAL_TTL_MS)})}
ipcMain.handle('chat:approval',(_,v)=>{const child=desktopChatProcess,aid=String(v?.approval_id||'');if(!child||!/^[a-f0-9]{32}$/i.test(aid))return {ok:false};const item=pendingChatApprovals.get(aid);if(!item)return {ok:false,error:'This approval has expired.'};clearTimeout(item.timer);pendingChatApprovals.delete(aid);child.stdin.write(JSON.stringify({type:'approval',approval_id:aid,session_id:item.sid,approve:v?.approve===true})+'\n');return {ok:true}});
let cloudIpcProcess=null,cloudIpcBuffer='',cloudIpcQueue=[],cloudIpcActive=null,cloudIpcErr='';
function finishCloudIpc(item,value){if(!item||cloudIpcActive!==item)return;clearTimeout(item.timer);cloudIpcActive=null;item.resolve(value);setImmediate(pumpCloudIpc)}
function ensureCloudIpc(){
  if(cloudIpcProcess&&!cloudIpcProcess.killed)return cloudIpcProcess;
  const a=agentExecutable(),{spawn}=require('child_process'),child=spawn(a.cmd,[...a.prefix,'cloud-ipc-jsonl'],{cwd:a.cwd,stdio:['pipe','pipe','pipe'],windowsHide:true});
  cloudIpcProcess=child;cloudIpcBuffer='';cloudIpcErr='';
  child.stdout.on('data',d=>{
    if(cloudIpcProcess!==child)return;
    cloudIpcBuffer+=d.toString('utf8');
    if(Buffer.byteLength(cloudIpcBuffer)>4*1024*1024){
      const item=cloudIpcActive;
      cloudIpcProcess=null;try{child.kill()}catch{}
      if(item)finishCloudIpc(item,{ok:false,error:'Cloud chat response too large'});
      return;
    }
    const lines=cloudIpcBuffer.split(/\r?\n/);cloudIpcBuffer=lines.pop()||'';
    for(const line of lines){
      if(!line.trim())continue;
      const item=cloudIpcActive;if(!item)continue;
      try{finishCloudIpc(item,JSON.parse(line))}
      catch{finishCloudIpc(item,{ok:false,error:'Invalid agent response'})}
    }
  });
  child.stderr.on('data',d=>{if(cloudIpcProcess===child){cloudIpcErr=(cloudIpcErr+d.toString('utf8')).slice(-256*1024)}});
  child.on('error',e=>{
    if(cloudIpcProcess!==child)return;
    cloudIpcProcess=null;
    const item=cloudIpcActive;
    if(item)finishCloudIpc(item,{ok:false,error:e.message});
  });
  child.on('exit',()=>{
    if(cloudIpcProcess!==child)return;
    cloudIpcProcess=null;
    const item=cloudIpcActive;
    if(item)finishCloudIpc(item,{ok:false,error:cloudIpcErr.trim().split(/\r?\n/).pop()||'Device Agent request failed.'});
    else setImmediate(pumpCloudIpc);
  });
  return child;
}
function pumpCloudIpc(){
  if((process.platform!=='win32'&&app.isPackaged)||cloudIpcActive||!cloudIpcQueue.length)return;
  let child;try{child=ensureCloudIpc()}catch(e){const item=cloudIpcQueue.shift();item.resolve({ok:false,error:e.message});return setImmediate(pumpCloudIpc)}
  const item=cloudIpcQueue.shift();cloudIpcActive=item;
  item.timer=setTimeout(()=>{
    if(cloudIpcActive!==item)return;
    const running=cloudIpcProcess;cloudIpcProcess=null;
    try{running?.kill()}catch{}
    finishCloudIpc(item,{ok:false,error:'Device Agent did not respond.'});
  },20000);
  child.stdin.write(JSON.stringify(item.request)+'\n',err=>{if(err&&cloudIpcActive===item)finishCloudIpc(item,{ok:false,error:err.message})});
}
function agentIpc(request){
  if(process.platform==='win32'||!app.isPackaged)return new Promise(resolve=>{cloudIpcQueue.push({request,resolve,timer:null});pumpCloudIpc()});
  return new Promise(resolve=>{const net=require('net'),sock=path.join(configRoot,'agent.sock'),client=net.createConnection(sock);let data='',done=false;const finish=v=>{if(done)return;done=true;client.destroy();resolve(v)};client.setTimeout(20000);client.on('connect',()=>client.write(JSON.stringify(request)+'\n'));client.on('data',d=>{data+=d.toString();if(Buffer.byteLength(data)>4*1024*1024)return finish({ok:false,error:'Cloud chat response too large'});const i=data.indexOf('\n');if(i>=0){try{finish(JSON.parse(data.slice(0,i)))}catch{finish({ok:false,error:'Invalid agent response'})}}});client.on('timeout',()=>finish({ok:false,error:'Device Agent did not respond.'}));client.on('error',e=>finish({ok:false,error:e.message}))})
}
app.on('before-quit',()=>{try{cloudIpcProcess?.kill()}catch{}});

ipcMain.handle('chat:cloud-list',(_,v)=>agentIpc({action:'cloud_chats_list',archived:v?.archived===true}));
ipcMain.handle('chat:cloud-get',(_,id)=>/^[0-9a-f-]{36}$/i.test(String(id||''))?agentIpc({action:'cloud_chat_get',session_id:String(id)}):({ok:false,error:'Invalid chat ID'}));
ipcMain.handle('chat:cloud-create',(_,v)=>agentIpc({action:'cloud_chat_create',title:String(v?.title||'New chat').slice(0,160),provider:String(v?.provider||'').slice(0,80),model:String(v?.model||'').slice(0,120)}));
ipcMain.handle('chat:cloud-add-message',(_,v)=>/^[0-9a-f-]{36}$/i.test(String(v?.session_id||''))?agentIpc({action:'cloud_chat_add_message',session_id:String(v.session_id),role:String(v.role||''),content:String(v.content||''),model:String(v.model||'').slice(0,120),tool_name:String(v.tool_name||'').slice(0,160),tool_data:v.tool_data??null}):({ok:false,error:'Invalid chat ID'}));
ipcMain.handle('chat:cloud-delete',(_,id)=>/^[0-9a-f-]{36}$/i.test(String(id||''))?agentIpc({action:'cloud_chat_delete',session_id:String(id)}):({ok:false,error:'Invalid chat ID'}));
ipcMain.handle('chat:cloud-update',(_,v)=>/^[0-9a-f-]{36}$/i.test(String(v?.session_id||''))?agentIpc({action:'cloud_chat_update',session_id:String(v.session_id),...(Object.prototype.hasOwnProperty.call(v,'title')?{title:String(v.title||'New chat').slice(0,160)}:{}),...(Object.prototype.hasOwnProperty.call(v,'is_pinned')?{is_pinned:v.is_pinned===true}:{}),...(Object.prototype.hasOwnProperty.call(v,'is_archived')?{is_archived:v.is_archived===true}:{})}):({ok:false,error:'Invalid chat ID'}));
ipcMain.handle('chat:export',async(_,v)=>{try{const format=v?.format==='json'?'json':'txt',title=String(v?.title||'chat').replace(/[\\/:*?"<>|]/g,'_').slice(0,80)||'chat',messages=Array.isArray(v?.messages)?v.messages:[],defaultPath=path.join(app.getPath('downloads'),`${title}.${format}`),r=await dialog.showSaveDialog({title:'Export chat',defaultPath,filters:[{name:format==='json'?'JSON':'Text',extensions:[format]}]});if(r.canceled||!r.filePath)return {ok:false,canceled:true};let data;if(format==='json')data=JSON.stringify({title:v?.title||'New chat',exported_at:new Date().toISOString(),messages},null,2);else data=messages.map(m=>`${String(m.role||'').toUpperCase()}\n${String(m.content||'')}\n`).join('\n');fs.writeFileSync(r.filePath,data,'utf8');return {ok:true,path:r.filePath}}catch(e){return {ok:false,error:e.message}}});
function tailFile(file,maxBytes=65536,maxLines=120){try{const st=fs.statSync(file);if(!st.size)return '';const n=Math.min(st.size,maxBytes),fd=fs.openSync(file,'r'),buf=Buffer.alloc(n);fs.readSync(fd,buf,0,n,st.size-n);fs.closeSync(fd);let text=buf.toString('utf8');if(st.size>n)text=text.slice(text.indexOf('\n')+1);return text.split('\n').slice(-maxLines).join('\n').trim()}catch{return ''}}
ipcMain.handle('logs:tail',(_,kind='agent')=>{if(!platform.logPath)return 'No Agent log entries yet.';const dir=path.dirname(platform.logPath),runtime=[tailFile(platform.logPath),tailFile(path.join(dir,'agent-error.log'))].filter(Boolean).join('\n');if(kind!=='errors')return runtime||'No Agent log entries yet.';const lines=runtime.split('\n'),out=[];for(let i=0;i<lines.length;i++){if(/\[ERROR\]|Traceback|Exception|RuntimeError|PermissionError|Unauthorized|Forbidden/i.test(lines[i]))out.push(...lines.slice(i,Math.min(i+8,lines.length)))}return [...new Set(out)].slice(-120).join('\n')||'No error entries.'});
ipcMain.handle('open:web',()=>shell.openExternal('https://app.mcptoai.com'));ipcMain.handle('open:legal',(_,page)=>shell.openExternal(page==='terms'?'https://app.mcptoai.com/terms':'https://app.mcptoai.com/privacy'));
app.whenReady().then(create);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)create()});
